// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SQLS_MoniToni_Redesign

#include "ui.h"

void ui_EndScreen_screen_init(void)
{
ui_EndScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_EndScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_flex_flow(ui_EndScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_EndScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
ui_object_set_themeable_style_property(ui_EndScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Dark_Shades);
ui_object_set_themeable_style_property(ui_EndScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark_Shades);
lv_obj_set_style_pad_left(ui_EndScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_EndScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_EndScreen, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_EndScreen, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TransactionStatusPanel = lv_obj_create(ui_EndScreen);
lv_obj_set_width( ui_TransactionStatusPanel, lv_pct(90));
lv_obj_set_height( ui_TransactionStatusPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TransactionStatusPanel, 32 );
lv_obj_set_y( ui_TransactionStatusPanel, 30 );
lv_obj_set_align( ui_TransactionStatusPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TransactionStatusPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_TransactionStatusPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_state( ui_TransactionStatusPanel, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( ui_TransactionStatusPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_TransactionStatusPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TransactionStatusPanel, lv_color_hex(0xCAE3B1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TransactionStatusPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TransactionStatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TransactionStatusPanel, lv_color_hex(0xFDDEA0), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_TransactionStatusPanel, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_TransactionStatusPanel, lv_color_hex(0xFCCBC7), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_TransactionStatusPanel, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_ErrorTransactionLabel = lv_label_create(ui_TransactionStatusPanel);
lv_obj_set_width( ui_ErrorTransactionLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ErrorTransactionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ErrorTransactionLabel, -34 );
lv_obj_set_y( ui_ErrorTransactionLabel, 6 );
lv_obj_set_align( ui_ErrorTransactionLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ErrorTransactionLabel,"ERROR");
lv_obj_add_flag( ui_ErrorTransactionLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_ErrorTransactionLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
ui_object_set_themeable_style_property(ui_ErrorTransactionLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Danger);
ui_object_set_themeable_style_property(ui_ErrorTransactionLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Danger);
lv_obj_set_style_text_font(ui_ErrorTransactionLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompleteTransactionLabel = lv_label_create(ui_TransactionStatusPanel);
lv_obj_set_width( ui_CompleteTransactionLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CompleteTransactionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CompleteTransactionLabel, -34 );
lv_obj_set_y( ui_CompleteTransactionLabel, 6 );
lv_obj_set_align( ui_CompleteTransactionLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_CompleteTransactionLabel,"COMPLETED");
lv_obj_add_flag( ui_CompleteTransactionLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_CompleteTransactionLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
ui_object_set_themeable_style_property(ui_CompleteTransactionLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Success);
ui_object_set_themeable_style_property(ui_CompleteTransactionLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Success);
lv_obj_set_style_text_font(ui_CompleteTransactionLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DeniedTransactionLabel = lv_label_create(ui_TransactionStatusPanel);
lv_obj_set_width( ui_DeniedTransactionLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DeniedTransactionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DeniedTransactionLabel, -34 );
lv_obj_set_y( ui_DeniedTransactionLabel, 6 );
lv_obj_set_align( ui_DeniedTransactionLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DeniedTransactionLabel,"DENIED");
lv_obj_remove_flag( ui_DeniedTransactionLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_DeniedTransactionLabel, lv_color_hex(0xFBA90A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DeniedTransactionLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DeniedTransactionLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutputPanelEndScreen = lv_obj_create(ui_EndScreen);
lv_obj_set_width( ui_OutputPanelEndScreen, lv_pct(90));
lv_obj_set_height( ui_OutputPanelEndScreen, lv_pct(80));
lv_obj_set_x( ui_OutputPanelEndScreen, 76 );
lv_obj_set_y( ui_OutputPanelEndScreen, 26 );
lv_obj_set_align( ui_OutputPanelEndScreen, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_OutputPanelEndScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_OutputPanelEndScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_OutputPanelEndScreen, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_OutputPanelEndScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_OutputPanelEndScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutputPanelEndScreen, lv_color_hex(0xD6E0DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutputPanelEndScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_OutputPanelEndScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_OutputPanelEndScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_OutputPanelEndScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_OutputPanelEndScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_OutputPanelEndScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_OutputPanelEndScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_OutputPanelEndScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ThankYouLabel = lv_label_create(ui_OutputPanelEndScreen);
lv_obj_set_width( ui_ThankYouLabel, lv_pct(100));
lv_obj_set_height( ui_ThankYouLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ThankYouLabel, -34 );
lv_obj_set_y( ui_ThankYouLabel, 6 );
lv_obj_set_align( ui_ThankYouLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ThankYouLabel,"TRANSACTION\nSUCCESSFULL\n\nSEE YOU SOON");
lv_obj_remove_flag( ui_ThankYouLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
ui_object_set_themeable_style_property(ui_ThankYouLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Success);
ui_object_set_themeable_style_property(ui_ThankYouLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Success);
lv_obj_set_style_text_letter_space(ui_ThankYouLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ThankYouLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ThankYouLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ThankYouLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DeniedLabel = lv_label_create(ui_OutputPanelEndScreen);
lv_obj_set_width( ui_DeniedLabel, lv_pct(100));
lv_obj_set_height( ui_DeniedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DeniedLabel, -34 );
lv_obj_set_y( ui_DeniedLabel, 6 );
lv_obj_set_align( ui_DeniedLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DeniedLabel,"PURCHASE PRODUCT IN MONITONI BEFORE PRESSING OPEN ");
lv_obj_add_flag( ui_DeniedLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_DeniedLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_DeniedLabel, lv_color_hex(0xFBA90A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DeniedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_DeniedLabel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_DeniedLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DeniedLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DeniedLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ErrorLabel = lv_label_create(ui_OutputPanelEndScreen);
lv_obj_set_width( ui_ErrorLabel, lv_pct(100));
lv_obj_set_height( ui_ErrorLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ErrorLabel, -34 );
lv_obj_set_y( ui_ErrorLabel, 6 );
lv_obj_set_align( ui_ErrorLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ErrorLabel,"SERVER ERROR\n---\nTRY AGAIN OR CONTACT STAFF");
lv_obj_add_flag( ui_ErrorLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_ErrorLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
ui_object_set_themeable_style_property(ui_ErrorLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Danger);
ui_object_set_themeable_style_property(ui_ErrorLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Danger);
lv_obj_set_style_text_letter_space(ui_ErrorLabel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ErrorLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ErrorLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ErrorLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

}
