// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SQLS_MoniToni_Redesign

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Light_Shades[2] = {0xF2F7F6, 0xF2F7F6};
const ui_theme_variable_t _ui_theme_alpha_Light_Shades[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Success[2] = {0x7DB942, 0x7DB942};
const ui_theme_variable_t _ui_theme_alpha_Success[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Main_Color[2] = {0xFFD712, 0xFFD712};
const ui_theme_variable_t _ui_theme_alpha_Main_Color[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Danger[2] = {0xF44336, 0xF44336};
const ui_theme_variable_t _ui_theme_alpha_Danger[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Dark_Shades[2] = {0x32565A, 0x32565A};
const ui_theme_variable_t _ui_theme_alpha_Dark_Shades[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_MONITONI_THEME;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

