// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void buttonpress_Animation( lv_obj_t *TargetObject, int delay);
void serverRequest_Animation( lv_obj_t *TargetObject, int delay);
void UserAction_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_StartUpScreen
void ui_StartUpScreen_screen_init(void);
lv_obj_t *ui_StartUpScreen;
lv_obj_t *ui_StartUpPanel;
lv_obj_t *ui_StartUpPanelLabel;
lv_obj_t *ui_StartUpErrorPanelLabel;
lv_obj_t *ui_OutputPanelStartUpScreen;
lv_obj_t *ui_SetupLabel;
lv_obj_t *ui_StartUpErrorLabel;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
void ui_event_ButtonSpin( lv_event_t * e);
lv_obj_t *ui_ButtonSpin;
lv_obj_t *ui_ButtonSpinLabel;
void ui_event_ButtonOpen( lv_event_t * e);
lv_obj_t *ui_ButtonOpen;
lv_obj_t *ui_ButtonOpenLabel;


// SCREEN: ui_ValidationScreen
void ui_ValidationScreen_screen_init(void);
lv_obj_t *ui_ValidationScreen;
lv_obj_t *ui_DoorStatusPanel;
lv_obj_t *ui_DoorOpenStatusLabel;
lv_obj_t *ui_DoorClosedStatusLabel;
lv_obj_t *ui_OutputPanelValidationScreen;
lv_obj_t *ui_ValidationStatusPanel;
lv_obj_t *ui_ValidationStatusLabel;
lv_obj_t *ui_AccessGrantedStatusLabel;
lv_obj_t *ui_AccessDeniedStatusLabel;
lv_obj_t *ui_UserActionPanel;
lv_obj_t *ui_UserOpenActionLabel;
lv_obj_t *ui_UserCloseActionLabel;


// SCREEN: ui_EndScreen
void ui_EndScreen_screen_init(void);
lv_obj_t *ui_EndScreen;
lv_obj_t *ui_TransactionStatusPanel;
lv_obj_t *ui_ErrorTransactionLabel;
lv_obj_t *ui_CompleteTransactionLabel;
lv_obj_t *ui_DeniedTransactionLabel;
lv_obj_t *ui_OutputPanelEndScreen;
lv_obj_t *ui_ThankYouLabel;
lv_obj_t *ui_DeniedLabel;
lv_obj_t *ui_ErrorLabel;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void buttonpress_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 100);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 255, 200 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_overshoot);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);
ui_anim_user_data_t *PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_1_user_data->target = TargetObject;
PropertyAnimation_1_user_data->val = -1;
lv_anim_t PropertyAnimation_1;
lv_anim_init(&PropertyAnimation_1);
lv_anim_set_time(&PropertyAnimation_1, 200);
lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_width );
lv_anim_set_values(&PropertyAnimation_1, 0, 15 );
lv_anim_set_path_cb( &PropertyAnimation_1, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_1, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_1, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_1, 0);
lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
lv_anim_set_early_apply( &PropertyAnimation_1, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_width );
lv_anim_start(&PropertyAnimation_1);
ui_anim_user_data_t *PropertyAnimation_2_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_2_user_data->target = TargetObject;
PropertyAnimation_2_user_data->val = -1;
lv_anim_t PropertyAnimation_2;
lv_anim_init(&PropertyAnimation_2);
lv_anim_set_time(&PropertyAnimation_2, 200);
lv_anim_set_user_data(&PropertyAnimation_2, PropertyAnimation_2_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_2, _ui_anim_callback_set_height );
lv_anim_set_values(&PropertyAnimation_2, 0, 15 );
lv_anim_set_path_cb( &PropertyAnimation_2, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_2, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_2, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_2, 0);
lv_anim_set_playback_delay(&PropertyAnimation_2, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_2, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_2, 0);
lv_anim_set_early_apply( &PropertyAnimation_2, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_2, &_ui_anim_callback_get_height );
lv_anim_start(&PropertyAnimation_2);

}
void serverRequest_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 255, 180 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);

}
void UserAction_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 800);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity );
lv_anim_set_values(&PropertyAnimation_0, 255, 100 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonSpin( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      eventSpinPressed( e );
}
}
void ui_event_ButtonOpen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      eventOpenPressed( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_StartUpScreen_screen_init();
ui_MainScreen_screen_init();
ui_ValidationScreen_screen_init();
ui_EndScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_StartUpScreen);
}
