// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Test

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_flex_flow(ui_MainScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_MainScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonSpin = lv_button_create(ui_MainScreen);
lv_obj_set_width( ui_ButtonSpin, lv_pct(90));
lv_obj_set_height( ui_ButtonSpin, lv_pct(40));
lv_obj_set_x( ui_ButtonSpin, -16 );
lv_obj_set_y( ui_ButtonSpin, 93 );
lv_obj_set_align( ui_ButtonSpin, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ButtonSpin,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ButtonSpin, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_ButtonSpin, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ButtonSpin, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonSpin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonSpin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonSpin, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonSpin, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonSpin, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonSpin, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonSpin, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonSpin, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonSpin, lv_color_hex(0xD60000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonSpin, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ButtonSpinLabel = lv_label_create(ui_ButtonSpin);
lv_obj_set_width( ui_ButtonSpinLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ButtonSpinLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ButtonSpinLabel, 18 );
lv_obj_set_y( ui_ButtonSpinLabel, -90 );
lv_obj_set_align( ui_ButtonSpinLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ButtonSpinLabel,"SPIN");
lv_obj_set_style_text_color(ui_ButtonSpinLabel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonSpinLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ButtonSpinLabel, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonOpen = lv_button_create(ui_MainScreen);
lv_obj_set_width( ui_ButtonOpen, lv_pct(90));
lv_obj_set_height( ui_ButtonOpen, lv_pct(40));
lv_obj_set_x( ui_ButtonOpen, -16 );
lv_obj_set_y( ui_ButtonOpen, 93 );
lv_obj_set_align( ui_ButtonOpen, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ButtonOpen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ButtonOpen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_ButtonOpen, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ButtonOpen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonOpen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonOpen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_ButtonOpen, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ButtonOpen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_ButtonOpen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_ButtonOpen, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_x(ui_ButtonOpen, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_offset_y(ui_ButtonOpen, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonOpen, lv_color_hex(0xD60000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonOpen, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ButtonOpenLabel = lv_label_create(ui_ButtonOpen);
lv_obj_set_width( ui_ButtonOpenLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ButtonOpenLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ButtonOpenLabel, 18 );
lv_obj_set_y( ui_ButtonOpenLabel, -90 );
lv_obj_set_align( ui_ButtonOpenLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ButtonOpenLabel,"OPEN");
lv_obj_set_style_text_color(ui_ButtonOpenLabel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonOpenLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ButtonOpenLabel, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);


}
