// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SQLS_MoniToni_Redesign

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_LIGHT_SHADES 0
#define UI_THEME_COLOR_SUCCESS 1
#define UI_THEME_COLOR_MAIN_COLOR 2
#define UI_THEME_COLOR_DANGER 3
#define UI_THEME_COLOR_DARK_SHADES 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_MONITONI_THEME 1

extern const ui_theme_variable_t _ui_theme_color_Light_Shades[2];
extern const ui_theme_variable_t _ui_theme_alpha_Light_Shades[2];

extern const ui_theme_variable_t _ui_theme_color_Success[2];
extern const ui_theme_variable_t _ui_theme_alpha_Success[2];

extern const ui_theme_variable_t _ui_theme_color_Main_Color[2];
extern const ui_theme_variable_t _ui_theme_alpha_Main_Color[2];

extern const ui_theme_variable_t _ui_theme_color_Danger[2];
extern const ui_theme_variable_t _ui_theme_alpha_Danger[2];

extern const ui_theme_variable_t _ui_theme_color_Dark_Shades[2];
extern const ui_theme_variable_t _ui_theme_alpha_Dark_Shades[2];

extern const uint32_t* ui_theme_colors[2];
extern const uint8_t* ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
