// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SQLS_MoniToni_Redesign

#ifndef _SQLS_MONITONI_REDESIGN_UI_H
#define _SQLS_MONITONI_REDESIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void buttonpress_Animation( lv_obj_t *TargetObject, int delay);
void serverRequest_Animation( lv_obj_t *TargetObject, int delay);
void UserAction_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_StartUpScreen
void ui_StartUpScreen_screen_init(void);
extern lv_obj_t *ui_StartUpScreen;
extern lv_obj_t *ui_StartUpPanel;
extern lv_obj_t *ui_StartUpPanelLabel;
extern lv_obj_t *ui_StartUpErrorPanelLabel;
extern lv_obj_t *ui_OutputPanelStartUpScreen;
extern lv_obj_t *ui_SetupLabel;
extern lv_obj_t *ui_StartUpErrorLabel;
extern lv_obj_t *ui_WIFILabel;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
void ui_event_ButtonSpin( lv_event_t * e);
extern lv_obj_t *ui_ButtonSpin;
extern lv_obj_t *ui_ButtonSpinLabel;
extern lv_obj_t *ui_ButtonOpen;
extern lv_obj_t *ui_ButtonOpenLabel;
// SCREEN: ui_ValidationScreen
void ui_ValidationScreen_screen_init(void);
extern lv_obj_t *ui_ValidationScreen;
extern lv_obj_t *ui_DoorStatusPanel;
extern lv_obj_t *ui_DoorOpenStatusLabel;
extern lv_obj_t *ui_DoorClosedStatusLabel;
extern lv_obj_t *ui_OutputPanelValidationScreen;
extern lv_obj_t *ui_ValidationStatusPanel;
extern lv_obj_t *ui_ValidationStatusLabel;
extern lv_obj_t *ui_AccessGrantedStatusLabel;
extern lv_obj_t *ui_AccessDeniedStatusLabel;
extern lv_obj_t *ui_UserActionPanel;
extern lv_obj_t *ui_UserOpenActionLabel;
extern lv_obj_t *ui_UserCloseActionLabel;
// SCREEN: ui_EndScreen
void ui_EndScreen_screen_init(void);
extern lv_obj_t *ui_EndScreen;
extern lv_obj_t *ui_TransactionStatusPanel;
extern lv_obj_t *ui_ErrorTransactionLabel;
extern lv_obj_t *ui_CompleteTransactionLabel;
extern lv_obj_t *ui_DeniedTransactionLabel;
extern lv_obj_t *ui_OutputPanelEndScreen;
extern lv_obj_t *ui_ThankYouLabel;
extern lv_obj_t *ui_DeniedLabel;
extern lv_obj_t *ui_ErrorLabel;
extern lv_obj_t *ui____initial_actions0;





void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
