// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SQLS_MoniToni_Redesign

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void eventSpinPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
