// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Test

#include "ui.h"

void ui_ValidationScreen_screen_init(void)
{
ui_ValidationScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ValidationScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_flex_flow(ui_ValidationScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ValidationScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_ValidationScreen, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ValidationScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ValidationScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ValidationScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ValidationScreen, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ValidationScreen, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DoorStatusPanel = lv_obj_create(ui_ValidationScreen);
lv_obj_set_width( ui_DoorStatusPanel, lv_pct(90));
lv_obj_set_height( ui_DoorStatusPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DoorStatusPanel, 32 );
lv_obj_set_y( ui_DoorStatusPanel, 30 );
lv_obj_set_align( ui_DoorStatusPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_DoorStatusPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_DoorStatusPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_state( ui_DoorStatusPanel, LV_STATE_CHECKED );     /// States
lv_obj_remove_flag( ui_DoorStatusPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_DoorStatusPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DoorStatusPanel, lv_color_hex(0xD60000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DoorStatusPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DoorStatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DoorStatusPanel, lv_color_hex(0x127800), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_DoorStatusPanel, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_DoorOpenStatusLabel = lv_label_create(ui_DoorStatusPanel);
lv_obj_set_width( ui_DoorOpenStatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DoorOpenStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DoorOpenStatusLabel, -34 );
lv_obj_set_y( ui_DoorOpenStatusLabel, 6 );
lv_obj_set_align( ui_DoorOpenStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DoorOpenStatusLabel,"DOOR CLOSED");
lv_obj_remove_flag( ui_DoorOpenStatusLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_DoorOpenStatusLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DoorClosedStatusLabel = lv_label_create(ui_DoorStatusPanel);
lv_obj_set_width( ui_DoorClosedStatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DoorClosedStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DoorClosedStatusLabel, -34 );
lv_obj_set_y( ui_DoorClosedStatusLabel, 6 );
lv_obj_set_align( ui_DoorClosedStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DoorClosedStatusLabel,"DOOR CLOSED");
lv_obj_add_flag( ui_DoorClosedStatusLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_DoorClosedStatusLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_DoorClosedStatusLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutputPanelValidationScreen = lv_obj_create(ui_ValidationScreen);
lv_obj_set_width( ui_OutputPanelValidationScreen, lv_pct(90));
lv_obj_set_height( ui_OutputPanelValidationScreen, lv_pct(80));
lv_obj_set_x( ui_OutputPanelValidationScreen, 76 );
lv_obj_set_y( ui_OutputPanelValidationScreen, 26 );
lv_obj_set_align( ui_OutputPanelValidationScreen, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_OutputPanelValidationScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_OutputPanelValidationScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_OutputPanelValidationScreen, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_OutputPanelValidationScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_OutputPanelValidationScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutputPanelValidationScreen, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutputPanelValidationScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_OutputPanelValidationScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_OutputPanelValidationScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_OutputPanelValidationScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_OutputPanelValidationScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValidationStatusPanel = lv_obj_create(ui_OutputPanelValidationScreen);
lv_obj_set_width( ui_ValidationStatusPanel, lv_pct(100));
lv_obj_set_height( ui_ValidationStatusPanel, lv_pct(45));
lv_obj_set_x( ui_ValidationStatusPanel, 32 );
lv_obj_set_y( ui_ValidationStatusPanel, 30 );
lv_obj_set_align( ui_ValidationStatusPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_ValidationStatusPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ValidationStatusPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_ValidationStatusPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_ValidationStatusPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ValidationStatusPanel, lv_color_hex(0x0003D6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ValidationStatusPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ValidationStatusPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ValidationStatusPanel, lv_color_hex(0x127800), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_ValidationStatusPanel, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_ValidationStatusPanel, lv_color_hex(0xD60000), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_ValidationStatusPanel, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_ValidationStatusLabel = lv_label_create(ui_ValidationStatusPanel);
lv_obj_set_width( ui_ValidationStatusLabel, lv_pct(100));
lv_obj_set_height( ui_ValidationStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValidationStatusLabel, -34 );
lv_obj_set_y( ui_ValidationStatusLabel, 6 );
lv_obj_set_align( ui_ValidationStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValidationStatusLabel,"VALIDATING PURCHASE");
lv_obj_add_flag( ui_ValidationStatusLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_ValidationStatusLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_letter_space(ui_ValidationStatusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_ValidationStatusLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ValidationStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValidationStatusLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AccessGrantedStatusLabel = lv_label_create(ui_ValidationStatusPanel);
lv_obj_set_width( ui_AccessGrantedStatusLabel, lv_pct(100));
lv_obj_set_height( ui_AccessGrantedStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AccessGrantedStatusLabel, -34 );
lv_obj_set_y( ui_AccessGrantedStatusLabel, 6 );
lv_obj_set_align( ui_AccessGrantedStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AccessGrantedStatusLabel,"ACCESS GRANTED");
lv_obj_add_flag( ui_AccessGrantedStatusLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_AccessGrantedStatusLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_letter_space(ui_AccessGrantedStatusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_AccessGrantedStatusLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AccessGrantedStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AccessGrantedStatusLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AccessDeniedStatusLabel = lv_label_create(ui_ValidationStatusPanel);
lv_obj_set_width( ui_AccessDeniedStatusLabel, lv_pct(100));
lv_obj_set_height( ui_AccessDeniedStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AccessDeniedStatusLabel, -34 );
lv_obj_set_y( ui_AccessDeniedStatusLabel, 6 );
lv_obj_set_align( ui_AccessDeniedStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AccessDeniedStatusLabel,"ACCESS DENIED");
lv_obj_remove_flag( ui_AccessDeniedStatusLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_letter_space(ui_AccessDeniedStatusLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_AccessDeniedStatusLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AccessDeniedStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AccessDeniedStatusLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UserActionPanel = lv_obj_create(ui_OutputPanelValidationScreen);
lv_obj_set_width( ui_UserActionPanel, lv_pct(100));
lv_obj_set_height( ui_UserActionPanel, lv_pct(45));
lv_obj_set_x( ui_UserActionPanel, 32 );
lv_obj_set_y( ui_UserActionPanel, 30 );
lv_obj_set_align( ui_UserActionPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_UserActionPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_UserActionPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_UserActionPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_UserActionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_UserActionPanel, lv_color_hex(0xD60000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_UserActionPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_UserActionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_UserActionPanel, lv_color_hex(0x127800), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_UserActionPanel, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_UserOpenActionLabel = lv_label_create(ui_UserActionPanel);
lv_obj_set_width( ui_UserOpenActionLabel, lv_pct(100));
lv_obj_set_height( ui_UserOpenActionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UserOpenActionLabel, -34 );
lv_obj_set_y( ui_UserOpenActionLabel, 6 );
lv_obj_set_align( ui_UserOpenActionLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_UserOpenActionLabel,"PLEASE OPEN DOOR");
lv_obj_add_flag( ui_UserOpenActionLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_UserOpenActionLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_letter_space(ui_UserOpenActionLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_UserOpenActionLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_UserOpenActionLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_UserOpenActionLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UserCloseActionLabel = lv_label_create(ui_UserActionPanel);
lv_obj_set_width( ui_UserCloseActionLabel, lv_pct(100));
lv_obj_set_height( ui_UserCloseActionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UserCloseActionLabel, -34 );
lv_obj_set_y( ui_UserCloseActionLabel, 6 );
lv_obj_set_align( ui_UserCloseActionLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_UserCloseActionLabel,"PLEASE CLOSE DOOR");
lv_obj_remove_flag( ui_UserCloseActionLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_letter_space(ui_UserCloseActionLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_UserCloseActionLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_UserCloseActionLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_UserCloseActionLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
