// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: SquareLine_Test

#include "ui.h"

void ui_StartUpScreen_screen_init(void)
{
ui_StartUpScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_StartUpScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_flex_flow(ui_StartUpScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_StartUpScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_event_cb(ui_StartUpScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_StartUpScreen);
lv_obj_set_style_bg_color(ui_StartUpScreen, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartUpScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_StartUpScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_StartUpScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_StartUpScreen, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_StartUpScreen, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartUpPanel = lv_obj_create(ui_StartUpScreen);
lv_obj_set_width( ui_StartUpPanel, lv_pct(90));
lv_obj_set_height( ui_StartUpPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StartUpPanel, 32 );
lv_obj_set_y( ui_StartUpPanel, 30 );
lv_obj_set_align( ui_StartUpPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_StartUpPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_StartUpPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_StartUpPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_StartUpPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartUpPanel, lv_color_hex(0x0003D6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartUpPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_StartUpPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartUpPanel, lv_color_hex(0x127800), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_StartUpPanel, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_StartUpPanel, lv_color_hex(0xD60000), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_StartUpPanel, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_StartUpPanelLabel = lv_label_create(ui_StartUpPanel);
lv_obj_set_width( ui_StartUpPanelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartUpPanelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StartUpPanelLabel, -34 );
lv_obj_set_y( ui_StartUpPanelLabel, 6 );
lv_obj_set_align( ui_StartUpPanelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartUpPanelLabel,"START UP");
lv_obj_remove_flag( ui_StartUpPanelLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_StartUpPanelLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartUpErrorPanelLabel = lv_label_create(ui_StartUpPanel);
lv_obj_set_width( ui_StartUpErrorPanelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StartUpErrorPanelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StartUpErrorPanelLabel, -34 );
lv_obj_set_y( ui_StartUpErrorPanelLabel, 6 );
lv_obj_set_align( ui_StartUpErrorPanelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartUpErrorPanelLabel,"ERROR");
lv_obj_add_flag( ui_StartUpErrorPanelLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_StartUpErrorPanelLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_font(ui_StartUpErrorPanelLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OutputPanelStartUpScreen = lv_obj_create(ui_StartUpScreen);
lv_obj_set_width( ui_OutputPanelStartUpScreen, lv_pct(90));
lv_obj_set_height( ui_OutputPanelStartUpScreen, lv_pct(80));
lv_obj_set_x( ui_OutputPanelStartUpScreen, 76 );
lv_obj_set_y( ui_OutputPanelStartUpScreen, 26 );
lv_obj_set_align( ui_OutputPanelStartUpScreen, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_OutputPanelStartUpScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_OutputPanelStartUpScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_OutputPanelStartUpScreen, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_remove_flag( ui_OutputPanelStartUpScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_OutputPanelStartUpScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OutputPanelStartUpScreen, lv_color_hex(0xF4F4F4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OutputPanelStartUpScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_OutputPanelStartUpScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_OutputPanelStartUpScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_OutputPanelStartUpScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_OutputPanelStartUpScreen, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetupLabel = lv_label_create(ui_OutputPanelStartUpScreen);
lv_obj_set_width( ui_SetupLabel, lv_pct(100));
lv_obj_set_height( ui_SetupLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetupLabel, -34 );
lv_obj_set_y( ui_SetupLabel, 6 );
lv_obj_set_align( ui_SetupLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetupLabel,"SETTING UP CONTROLLER & CONNECTING TO NETWORK");
lv_obj_add_flag( ui_SetupLabel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_SetupLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_SetupLabel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetupLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_SetupLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_SetupLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetupLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetupLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartUpErrorLabel = lv_label_create(ui_OutputPanelStartUpScreen);
lv_obj_set_width( ui_StartUpErrorLabel, lv_pct(100));
lv_obj_set_height( ui_StartUpErrorLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StartUpErrorLabel, -34 );
lv_obj_set_y( ui_StartUpErrorLabel, 6 );
lv_obj_set_align( ui_StartUpErrorLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_StartUpErrorLabel,"ERROR OCCURRED\n--\nRESET SYSTEM OR CHECK DEBUG LOG ON SD CARD FOR FURTHER INFORMATION");
lv_obj_remove_flag( ui_StartUpErrorLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_StartUpErrorLabel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StartUpErrorLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_StartUpErrorLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_StartUpErrorLabel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_StartUpErrorLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StartUpErrorLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

}
